### ISSUE TITLE
[Priority] Start page

### ISSUE THREAD

**Issue by DaniellMesquita** [AnthyG/ThunderWave#108]

**Comment by AnthyG** [comment]
This is a duplicate of #65.
If not, please consider explaining further.

**Comment by DaniellMesquita** [comment]
I already explained it on Git Center.

**Comment by DaniellMesquita** [comment]
Start page with messages history and "New message" button.
User can also pin messages in this page.

**Comment by krixano** [comment]
He was saying if it's **not a duplicate** then explain.
