### ISSUE TITLE
User can choose message format: balloon or "square"

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#11]

**Comment by AnthyG** [comment]
So "square" would be like it is now, and "balloon" like discussed in #4?

**Comment by Plasmmer** [comment]
Yes.

**Comment by AnthyG** [comment]
This has been implemented with 1fe352e0b6e63fb8a0d8fe858983f23fdf0d701c.

**Comment by Plasmmer** [comment]
Can you make the "arrow at top" the default option?
