### ISSUE TITLE
Say if is a photo or a GIF

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#13]

**Comment by AnthyG** [comment]
What do you mean by that, @Plasmmer?

**Comment by mkg20001** [comment]
Probably a small "GIF" icon in the bottom right of the image

**Comment by Plasmmer** [comment]
Yes. User needs a discerniment of what image format he is going to download.

**Comment by AnthyG** [comment]
Added with 907c33ed99bccb55a7b541946fac692e4d5e4b07
