### ISSUE TITLE
Emoticon images are failing

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#20]

**Comment by AnthyG** [comment]
Could you please explain more :?

**Comment by Plasmmer** [comment]
The images are marked as "not found". I think its a optional files issue.

**Comment by AnthyG** [comment]
**ALL** Emoji's?
Because I'm sure, for others they work 🤔
Anything visiting [this URL](http://127.0.0.1:43110/1CWkZv7fQAKxTVjZVrLZ8VHcrN6YGGcdky/css/png/00a9.png)?

**Comment by Plasmmer** [comment]
Visit it in a proxy.

**Comment by AnthyG** [comment]
I've currently actually got the problem, that I don't see any Images 😞:thinking:

**Comment by AnthyG** [comment]
I believe this issue is actually the fault of the proxies, that probably cache the files, which may take some time, as there are quite some png-files for all the emoji's.

I also tested ThunderWave on [bit.surf](https://bit.surf:43110/1CWkZv7fQAKxTVjZVrLZ8VHcrN6YGGcdky), where `js/all.js` doesn't seem to update!
So I am pretty certain, this is the fault of the proxies (at least that of bit.surf)... 😞

**Comment by Plasmmer** [comment]
@mkg20001, emojis images works for you?
Here isn't working since the begin, even locally.

**Comment by AnthyG** [comment]
Ok, I seem to have forgotten to exclude the "css/png"-directory from being excluded in signing.
Now all files "css/png" have been signed, and it should work!

**Comment by Plasmmer** [comment]
Wait. User need to download ALL emojis? No. Make them as optional files.
![emojis](https://cloud.githubusercontent.com/assets/6765277/24931895/77147a76-1ee5-11e7-8b15-7b3fd4c23e32.png)

**Comment by AnthyG** [comment]
OMG 😲
I didn't understand how to do it, till now!
But I did it! :tada:

😆

**Comment by Plasmmer** [comment]
After "modified" line, add it to your content.json
` "optional": "({desiredfolder}/.*)",`

Change `{desiredfolder}` to the folder you want to make optional.

**Comment by AnthyG** [comment]
Yeah, I know it now, but the directory was also included in the "ignore"-property, so it wouldn't sign..
But as everything seems ok now, I'll close this Issue.
