### ISSUE TITLE
Users list

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#22]

**Comment by AnthyG** [comment]
I will rather create a "last seen"-List, as in a network like ZeroNet, it's, as far as I am aware of, not possible (yet) to list all users that are currently online!

**Comment by Plasmmer** [comment]
Yes, it can flood the network. Sorry for my mistake.

**Comment by AnthyG** [comment]
Added "last-seen-List"-Feature with commit 71fe1b1d0481c2e9ee06dbb1e855d668ece1ec56
