### ISSUE TITLE
Yellow triangle "in development zite" message instead of red exclamation

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#27]

**Comment by AnthyG** [comment]
What's the name of that "yellow triangle"?

**Comment by Plasmmer** [comment]
It is an type of notification as alert.

- Green with V is successs;
- Yellow with triangle is alert;
- Red with exclamation is error.

**Comment by AnthyG** [comment]
Hmm, actually I just checked [the Docs](http://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#wrappernotification-type-message-timeout), and it says that "type"-Property can only be one of the following `info`, `error`, or `done`.
Info being a blue-surrounded `i`.
So maybe I'll just take that?

**Comment by AnthyG** [comment]
Fixed with 951624dc04efa5e2b89b7bd695aa26b6774af808.
