### ISSUE TITLE
Themes feature: light or dark

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#28]

**Comment by AnthyG** [comment]
Somebody should (maybe I'll do it, when I'm finished with other things) fork [my fork](https://github.com/AnthyG/spectre-dark) of [Spectre.css](https://picturepan2.github.io/spectre/), and change the background-color back to default, like in the original.

**Comment by AnthyG** [comment]
This has been added with commit 9eb123b4fffd351b73cd96b0b0d2d4b62521a93d
