### ISSUE TITLE
If emojis are disabled, delete all from storage

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#29]

**Comment by AnthyG** [comment]
I think it would be better, to have an option to disable emoji's, like suggested in #25, but then not delete them, when this option is selected, but actually provide another option to delete them.

**Comment by AnthyG** [comment]
Somebody has to verify, that commit fcc4f8ee740acf7e78a2f3d59e7cb204ecaa76dd added the ability to delete all Emoji's.
The option is available in the "Settings"-Tab.

Please keep the console open, to verify that they actually have been deleted (there should be some messages, saying "deleted emoji at path ...").
Also, check the Zites `css/png`-Directory, to have a final verification!

**Comment by AnthyG** [comment]
@Plasmmer, could you verify, that this works?

**Comment by Plasmmer** [comment]
The files aren't removed.

![screenshot_2](https://cloud.githubusercontent.com/assets/6765277/24971588/d980e56a-1f8e-11e7-8180-2f57f39cdbd0.png)

**Comment by Plasmmer** [comment]
Also, I suggest to show a confirmation notification saying the number of emojis deleted.

**Comment by AnthyG** [comment]
Could you try again @Plasmmer?
(You'll have to reset the options once again!)
Please also check the developers console of your browser for this message `deleted emoji at path ...`.

**Comment by Plasmmer** [comment]
I received this message, but they are not deleted.

**Comment by AnthyG** [comment]
🤔 I can't delete them, as I am the only one, who has all emoji's, but I can show which would get deleted:
![image](https://cloud.githubusercontent.com/assets/15957203/24972212/de7e9284-1fba-11e7-8262-cac7f97664ce.png)

So I am a little bit confused why this won't work 🤔

**Comment by AnthyG** [comment]
@Plasmmer, did you activate (the switch has to be colored) the option "Disable loading of Emoji's"?
![image](https://cloud.githubusercontent.com/assets/15957203/24972640/640da308-1fbc-11e7-901d-bb2cfa65ad32.png)

**Comment by Plasmmer** [comment]
Activated.

**Comment by AnthyG** [comment]
Did you retry, after resetting to default?

**Comment by AnthyG** [comment]
@Plasmmer, does the function of deleting an optional media file, work for you?

**Comment by AnthyG** [comment]
The button "Delete all Emoji's" brought this feature in already.
