### ISSUE TITLE
Add meta keywords

### ISSUE THREAD

**Issue by DaniellMesquita** [AnthyG/ThunderWave#31]
I want to index ThunderWave in [Snifferdog](http://127.0.0.1:43110/snifferdog.bit/), but your site needs keywords.

**Comment by AnthyG** [comment]
Could you explain more?
Do I just have to add the normal "meta"-Tag in `index.html`?

**Comment by Plasmmer** [comment]
Add it, containing the keywords. Then tell me in the chat the keywords used.

**Comment by AnthyG** [comment]
👌

**Comment by AnthyG** [comment]
The keywords are `beautiful` `chat` `thunder` `wave` `thunderwave`
I don't have any more ideas :laughing:

**Comment by AnthyG** [comment]
Also added them to `index.html` with 58b92a2266fb471d8efd15460e903e8cb6d116dd and 128ceee3f5524d1824cbe0b15e09e542f7d8a07c.

**Comment by AnthyG** [comment]
Ah, I have another keyword: `social`

**Comment by Plasmmer** [comment]
Please update it in your html.

**Comment by AnthyG** [comment]
Is done. 9c3cb445c98e86cc520a6d96d11b74bb61502e1b

**Comment by DaniellMesquita** [comment]
@AnthyG
Is ThunderWave on 0list?

**Comment by AnthyG** [comment]
@DaniellMesquita, I don't know

**Comment by DaniellMesquita** [comment]
It is listed.

**Comment by DaniellMesquita** [comment]
It is listed.
