### ISSUE TITLE
Speech balloon message design

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#4]

**Comment by AnthyG** [comment]
What's wrong with the design ❔

**Comment by Plasmmer** [comment]
I'm not talking something is wrong, I'm just suggesting a speech balloon design.

**Comment by AnthyG** [comment]
Isn't the message-design "speech-balloon"-enough? 😆

**Comment by Plasmmer** [comment]
I'm suggesting something like this concept I've made in 2014:
![communicator_app_by_daniellmesquito-daig3l1](https://cloud.githubusercontent.com/assets/6765277/24905567/cea0f536-1e8a-11e7-9f37-520ff1cd4c64.png)
You're authorized to use it in ThunderWave.

**Comment by AnthyG** [comment]
So you just need that little extra arrow 💭 ?

(That shouldn't be that hard, I believe 🤔)

**Comment by Plasmmer** [comment]
It can be done with just CSS.
You can use the ":after" selector.

**Comment by AnthyG** [comment]
![image](https://cloud.githubusercontent.com/assets/15957203/24906538/6230879e-1eb8-11e7-855b-04f22c5805ee.png)
![image](https://cloud.githubusercontent.com/assets/15957203/24906541/64ca1074-1eb8-11e7-95fb-07574827e2e3.png)

What would do you prefer (maybe both, to let the user decide?)?

**Comment by Plasmmer** [comment]
The design from bottom is better. I don't think this is a great difference to user need to decide.

**Comment by AnthyG** [comment]
Hmm, didn't check GitHub for 20minutes, so I just added both as options 😆
1fe352e0b6e63fb8a0d8fe858983f23fdf0d701c

**Comment by Plasmmer** [comment]
Can you make the "arrow at top" the default option?
