### ISSUE TITLE
App icon in topbar

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#5]

**Comment by AnthyG** [comment]
#1 should be completed first to achieve this.

**Comment by Plasmmer** [comment]
I already have a icon (I've made in 2013).

**Comment by AnthyG** [comment]
@Plasmmer could you upload it here?

**Comment by Plasmmer** [comment]
![icon](https://cloud.githubusercontent.com/assets/6765277/24905369/2fc5f286-1e8a-11e7-9869-0551eedabddc.png)

**Comment by AnthyG** [comment]
Ui (astonished), that doesn't look bad!
But I don't think ThunderWave will support calls, so maybe without the phone, and in the primary-color (`#1DE9B6`)?
Though I have to admit, that would probably look quite empty 🤔

**Comment by Plasmmer** [comment]
I think (#1DE9B6) will be a very bright color for a icon. Maybe ThunderWave can support calls in the future, but really for now this icon doesn't matter.

**Comment by Plasmmer** [comment]
Updated with a thunder/wave:
![icon](https://cloud.githubusercontent.com/assets/6765277/24906185/1479edea-1e8d-11e7-9e6b-602fa1f29123.png)

**Comment by AnthyG** [comment]
This has been added in a commit quite some time ago.
