### ISSUE TITLE
Play button for GIFs

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#50]
This is opt-out to the user.

**Comment by AnthyG** [comment]
This *is* possible, but for the sake of looking good, there would also need to be something like a cover-image, which would be just one frame from the gif-File.

[Link 1](http://stackoverflow.com/questions/40947921/adding-a-play-pause-button-on-an-animated-gif-without-being-taken-to-the-url-of), [Link 2](http://stackoverflow.com/questions/4645274/extracting-single-frames-from-an-animated-gif-to-canvas).
Link 1 led me to [this JS-Library](https://github.com/krasimir/gifffer), and Link 2 led me to [this](https://github.com/buzzfeed/libgif-js), so..

**Comment by AnthyG** [comment]
Added with commit f65712ba8a9d0df3d18983c47d577962aa5f4a60
