### ISSUE TITLE
Material Design icon font

### ISSUE THREAD

**Issue by DaniellMesquita** [AnthyG/ThunderWave#59]

**Comment by AnthyG** [comment]
I don't really know, why I should include Font Awesome, I mean, aren't Emoji's enough?

**Comment by Plasmmer** [comment]
For the UI buttons, like ZeroMe Reloaded and Peeper does.

**Comment by AnthyG** [comment]
I'd rather use Google's Material Design Icon Font, just FYI

**Comment by Plasmmer** [comment]
Good.

**Comment by Plasmmer** [comment]
You can tag it as "help wanted".

**Comment by Plasmmer** [comment]
Please assign me to it.

**Comment by AnthyG** [comment]
This is included in ThunderWave Beta.

**Comment by AnthyG** [comment]
Yes, they are from Google's Material Design Icons.
