### ISSUE TITLE
Private messages (based in ZeroMail)

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#6]

**Comment by AnthyG** [comment]
This will be one of the main features, as (I believe) *ALL* "chat"-applications have got this!

The features:
 - end2end-Encrypted
 - both Users have the complete Chat-History (Encrypted, only readable with their own private key, and not being seeded)
 - Avatar and Username are displayed (maybe at the top?)

**Comment by AnthyG** [comment]
It seems, that there's currently no way to directly connect to another peer, thus, the 2nd item in the list will have to be abandoned,.. at least for now.

**Comment by Plasmmer** [comment]
@mkg20001

**Comment by mkg20001** [comment]
There is a function that one can use to encrypt/decrypt stuff with the key.
https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/?highlight=eciesEncrypt

**Comment by AnthyG** [comment]
I know 😄

**Comment by AnthyG** [comment]
I've got the private chat working,.. basically..

The only problem I'm encountering right now, is that the sender can't read his own messages, as they are encrypted with the public key of the recipient, who is the only one who can read the messages sent to him, as he is the only one, who has his own private key.

So I could save all the messages sent, into another file, which doesn't get seeded, as I already described in [the first comment I wrote in this Issue](#issuecomment-293216953), **but**, anybody who has the private key of the sender, would then be able to read *ALL* the messages he sent, and received.
And that is not really good I think, is it!? 👎

**Comment by mkg20001** [comment]
Why not encrypt them twice. With your own and the receivers public key?

**Comment by AnthyG** [comment]
@mkg20001 what exactly do you mean with password-protecting the chat? Which chat?

**Comment by AnthyG** [comment]
The idea with encrypting twice is pretty good!
I'm trying it right now :)

**Comment by AnthyG** [comment]
Created branch [private_chats-Feature](https://github.com/AnthyG/ThunderWave/tree/private_chats-Feature)

**Comment by AnthyG** [comment]
# It works!
Though I couldn't get the double-encryption working, that @mkg20001 suggested 😞
And I tried getting it to work for about 1hour now, so I will rethink it another time, but my brain is just to cluttered to get anything else working..

The two commits:
e32cbec2a9f3261c3860554fdd85e524d7b4cfb9, 3ec8b701ebce350233ec1dd6c596df4c59565ae4

Here's a preview:
(Note, I haven't yet added input's, and I actually created a contact-list-like thingy, but it doesn't quite seem to work, as it just resets whenever the user sends a message,.. *and I really don't know why*)

![image](https://cloud.githubusercontent.com/assets/15957203/25056223/b1c22a7c-2167-11e7-91d6-60ff2f89e164.png)

**Comment by AnthyG** [comment]
I just tried several tests, and the IV and AES-Key (that are the same: `btoa(recipient)` (base64)) are actually just too short...................
# WOW

**Comment by AnthyG** [comment]
Added working user-selection tabs and message-input for private chat with a924ff4a0c651f2d0e2db2be7006b0df1d5f5eac.

*But I won't guarantee anything for now..*

**Comment by AnthyG** [comment]
Commit b578b6b797313f777047361eb98d0a11b7b84c16 added the ability to click a users public key, listed in the "Last seen"-Tab, to open up a private chat with said user.

**Comment by AnthyG** [comment]
Fixed some things with commit 4c14024e3753343c113e989df55bfd9a1bf5900b

**Comment by AnthyG** [comment]
Changed a few things with commit 34190c11e6af9ac1d8fc5a85442dfb81f583337c

**Comment by AnthyG** [comment]
I will close this issue, as the basic functions of the private chat have been added with previous commits.
For new bugs found/ ideas/ improvements for the private chat, new issues can be created.
