### ISSUE TITLE
Media Upload doesn't work properly anymore

### ISSUE THREAD

**Issue by AnthyG** [AnthyG/ThunderWave#61]
Pretty much don't know anything about this yet, so I will just leave it like this for now..

**Comment by AnthyG** [comment]
It's because I messed up with the HTML-elements, so should be easy to fix.

**Comment by Plasmmer** [comment]
You can add it to a priority milestone.

**Comment by AnthyG** [comment]
Finally fixed with commit dd4377c63ec85bfdc88173e67980fd82672f57de
