### ISSUE TITLE
Show users that are typing a message

### ISSUE THREAD

**Issue by Plasmmer** [AnthyG/ThunderWave#83]

**Comment by AnthyG** [comment]
Is this a good idea in the Lobby?
Because if ThunderWave gets even more users, and then a lot type in the Lobby, this might be to crowded..
Or there could be something like "Glightstar, Plasmmer, and x others are typing..."

**Comment by Plasmmer** [comment]
Yes.

**Comment by AnthyG** [comment]
After a second though, this is actually quite hard to achieve in ZeroNet..
Because it would require that the user signs and publishes after each time setting `is_typing` to either `true` or `false`

So I will have to think about this.

**Comment by AnthyG** [comment]
Ok, I will close this issue, as I won't be adding the requested feature, because it's just not really possible in ZeroNet.
If "you" have any idea, on how it could be achieved, please consider commenting here/ re-opening this issue!
