### ISSUE TITLE
Better mobile display

### ISSUE THREAD

**Issue by DaniellMesquita** [AnthyG/ThunderWave#86]

**Comment by Plasmmer** [comment]
Please tag it as "help wanted" and assign me.

**Comment by AnthyG** [comment]
@Plasmmer because of AngularJS?

**Comment by Plasmmer** [comment]
With Angular or not, ThunderWave isn't working well in mobile.

**Comment by AnthyG** [comment]
Probably because I didn't use all of Spectre.css's stuff for responsiveness..
But this will probably be fixed with AngularJS anyways, right?

**Comment by Plasmmer** [comment]
Right.

**Comment by AnthyG** [comment]
This is covered with the re-design that is being worked on for ThunderWave Beta.
